Lab6/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
app_name = 'Lab6'



#path for app
urlpatterns = [
    path('status/', views.index, name='index'),
    path('delete/', views.delete_obj, name='delete'),
    path('', views.profil, name='profil'),
    path('daftarbuku/api/library/<str:teks>/', views.books, name='books'),
    path('daftarbuku/',views.daftarbuku,name='daftarbuku'),
    path('regis/', views.regis, name = 'regis'),
    path('add_subs/', views.add_subs, name = 'add_subs'),
    path('show_subs/',views.show_subs,name='show_subs'),
    path('delete_subs/',views.delete_subs,name='delete_subs'),
    path('login/',views.login,name='login'),
    path('logoutt/',views.logout_views,name='logout_views'),



]

ppwlab-6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import Lab6.urls as Lab6


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(Lab6), name='Lab6'),
    path('auth/', include('social_django.urls', namespace='social')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Lab6/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Status(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True, null=True)

class Subscriber(models.Model):
    email = models.CharField(max_length = 30, unique = True, db_index=True)
    name = models.CharField(max_length = 30)
    password = models.CharField(max_length = 15)

Lab6/forms.py
from django import forms
from .models import Status
from datetime import datetime


class Status_Form(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']
        widgets = {
            'status': forms.Textarea(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(Status_Form, self).__init__(*args, **kwargs)
        self.fields['status'].label = "Masukkan status disini"

class Subscribe_Form(forms.Form):
    error_messages={
        'required':'Required Field'
    }
    name_attrs={
        'type':'text',
        'class':'form-control',
        'placeholder': 'Required'
    }
    email_attrs={
        'type':'email',
        'class': 'form-control',
        'placeholder':'Required'
    }
    password_attrs={
        'type':'password',
        'class':'form-control',
        'placeholder':'Required'
    }

    name = forms.CharField(
        label='Name',
        required = True,
        widget=forms.TextInput(attrs=name_attrs)
    )

    email = forms.EmailField(
        label='Email',
        required=True,
        max_length=30,
        widget=forms.EmailInput(attrs=email_attrs)
    )

    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs=password_attrs)
    )

Lab6/views.py
from django.shortcuts import render,redirect
from .forms import Status_Form
from .models import Status
from .forms import Subscribe_Form
from .models import Subscriber
from django.http import JsonResponse
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.http import HttpResponseBadRequest
from django.http import HttpResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout
from datetime import datetime,date

import urllib.request, json
import requests


# Create your views here.

response = {}

def index(request):
    if request.method == 'POST':
        form = Status_Form(request.POST)
        statuses = Status.objects.all().order_by('date')
        if form.is_valid():
            status = Status(status=form.cleaned_data['status'])
            status.save()
            return redirect('Lab6:index')

    else:
        form = Status_Form()
        statuses = Status.objects.all().order_by('date')
    return render(request, 'index.html', {'form': form, 'statuses': statuses})

def delete_obj(request):
    Status.objects.all().delete()
    return redirect('Lab6:index')


def profil(request):
    return render(request, 'profil.html')

def books(request, teks):
    raw = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + teks).json()
    itemss = []
    for i in raw['items']:
        data = {}
        data['title'] = i['volumeInfo']['title']
        data['thumbnail'] = i['volumeInfo']['imageLinks']['thumbnail'] if 'imageLinks' in i['volumeInfo'].keys() else 'Tidak ada'
        data['authors']= ", ".join(i['volumeInfo']['authors']) if 'authors' in i['volumeInfo'].keys() else 'Tidak ada'
        data['publishedDate'] = i['volumeInfo']['publishedDate'] if 'publishedDate' in i['volumeInfo'].keys() else 'Tidak ada'
        itemss.append(data)
    return JsonResponse({"data" : itemss})

def daftarbuku(request):
    return render(request,'daftarbuku.html')



def regis(request):
    form = Subscribe_Form(request.POST)
    html = 'subscribe.html'
    return render(request,html,{'form':form})

def add_subs(request):
    response['form'] = Subscribe_Form()
    form = Subscribe_Form(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        response['name'] = request.POST['name']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        status = 'True'
        #Store account into subscribers database
        try:
            storedata = Subscriber(
            name=response['name'],
            email=response['email'],
            password=response['password']
            )
            storedata.save()
            return JsonResponse({'status':status})
        except IntegrityError as e:
            status = 'False'
            return JsonResponse({'status':status})
    status = 'False'
    return JsonResponse({'status':status})

def show_subs(request):
    data = list( Subscriber.objects.all().values('pk','name','email','password'))
    return JsonResponse({'subsdata':data})

@csrf_exempt
def delete_subs(request):
    if(request.method == 'POST'):
        subsdata = request.POST['pk']
        Subscriber.objects.filter(pk=subsdata).delete()
        return HttpResponse({'status':'Unsubscribe success!'})
    else:
        return HttpResponse({'status':'Failed to load page'})



def login(request):
    form = Subscribe_Form()
    return render(request,'login.html',{"form":form})

def logout_views(request):
    logout(request)
    return redirect('Lab6:daftarbuku')

Lab6/templates/daftarbuku.html
{% extends "navbar.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
  Story PPW
{% endblock title %}

{% block extrahead %}
    <link rel="stylesheet" type= 'text/css' href="{% static 'style.css' %}">
    <script src="{% static 'js/Lab6.js' %}"></script>
{% endblock %}

{% block content %}

<div class="alert alert-success">
  {% if user.is_authenticated %}
               <h5 class="helloLogin">Hello, {{ user.username }}</h5>
      {% else %}
               <a class="lead" href="{% url 'Lab6:login' %}">Log in</a>
      {% endif %}
</div>


<div class="row center">
    <div class="col-sm-12">
        <h1 class="center-text" id="library">My Library</h1>
    </div>
</div>

<center>
    <button type="button" class="btn btn-dark" id="architecture">Architecture</button>
    <button type="button" class="btn btn-dark" id="comic">Comic</button>
    <button type="button" class="btn btn-dark" id="quilting">Quilting</button>
</center>

<div class="counter-container">
  <i class ="fa fa-star"></i>: <span class="counters">0</span>
</div>
<table class="table table-dark">
  <thead> <tr>
    <th scope="col"> No.</th>
    <th scope="col"> Title</th>
    <th scope="col"> Cover</th>
    <th scope="col"> Author</th>
    <th scope="col"> Published date</th>
    <th scope="col"> Favorites</th>
  </tr> </thead>
  <tbody> </tbody>
</table>

{% endblock %}

Lab6/templates/index.html
{% extends "navbar.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
  Story PPW
{% endblock title %}

{% block css %}
    <link rel="stylesheet" type= 'text/css' href="{% static 'style.css' %}">
{% endblock css %}

{% block content %}

    <div class="container">
        <div class="row center">
            <div class="col-sm-12">
                <h1 class="center-text" id="hello">Hello, Apa kabar?</h1>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <form class="form-group" action="{% url 'Lab6:index' %}" method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                <input type="submit" id="submit-button" class="btn btn-success" value="Submit">
                <a href="{% url 'Lab6:delete' %}" class="btn btn-danger" id="delete_button">Delete</a>
                </form>

          </div>
          <div class="container">
              <br>
              {% for status in statuses %}
                  <div class="col-sm-6" id="stat">
                      <h5>Date: {{status.date}}</h5>
                      <h5>Status: {{status.status}}</h5>
                  </div>
              {% endfor %}
          </div>
      </div>
  {% endblock %}

Lab6/templates/login.html
{% extends 'navbar.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
  Story PPW
{% endblock title %}

{% block extrahead %}
    <link rel="stylesheet" type= 'text/css' href="{% static 'style.css' %}">
    <script src="{% static 'js/Lab6.js' %}"></script>
{% endblock %}

{% block content %}
<center>
	<h2>Login</h2>
  <form method="post">
    {% csrf_token %}
  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
</center>
{% endblock %}

Lab6/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=n">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>
      {% block title %}
      Story PPW
      {% endblock title %}
    </title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="{% static "js/Lab6.js" %}"></script>
    <script type="text/javascript" src="{% static "js/story10.js" %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
      <link rel="stylesheet" type= 'text/css' href="{% static 'style.css' %}">
    {% endblock css %}
  </head>
<body style="margin-top:100px">
  <header>
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
        <a class="navbar-brand" href="../profil">Salsabila Maurizka</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-link" href="../">Profil<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="../status">Status Form</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="../daftarbuku">Library</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="../regis">Subscribe</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="../logoutt">Logout</a>
              </li>
            </ul>
        </div>
    </nav>
  </header>

  <div class="container">
      {% block content %}
      <!--Tulis content disini-->
      {% endblock %}
  </div>
  </body>
</html>

Lab6/templates/profil.html
{% extends "navbar.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
  Story PPW
{% endblock title %}

{% block css %}
    <link rel="stylesheet" type= 'text/css' href="{% static 'style.css' %}">
{% endblock css %}

{% block content %}



<body onload="myFunction()" style="margin:0;">
  <div id="loader"></div>

  <div style="display:none;" id="myDiv" class="animate-bottom">
    <div class="container text-left">
      <h3 class="btn btn-dark" id="id_change">Change Theme</h3>
    </div>
    <div class="container text-center">
        <div class="text-center">
            <img id="profilphotos" src="https://scontent-sin2-2.xx.fbcdn.net/v/t1.0-9/42058749_1397298703736008_1790833012598898688_n.jpg?_nc_cat=103&_nc_ht=scontent-sin2-2.xx&oh=36adfd368a9f046f43cbe1f1173afab3&oe=5C472B2E" class="rounded-circle"   width="20%" height="30%" data-toggle="tooltip" data-placement="top" title="Ini foto saya!">
            <h3 class="font-weight-bold">Salsabila Maurizka</h3>
            <h6>1706043986</h6>
            <h6>Fakultas Ilmu Komputer, Universitas Indonesia</h6>
        </div>
      <div class="accordion">
          <h3 class="btn-warning rounded" id="acc">Activities</h3>
          <div class="bg-white" id="acc-panel">
            <p>Studying PPW and SDA everyday</p>
          </div>
          <h3 class="btn-warning rounded" id="acc">Organization/Committee</h3>
          <div class="bg-white" id="acc-panel">
            <p>DPM FASILKOM UI 2018</p>
            <p>KOMUNITAS MAHASISWA PURWOREJO(KOMPOR) 2018</p>
            <p>EDUCARE 2019</p>
            <p>WISUDA GANJIL FASILKOM 2019</p>
            <p>SIGEMPUR 2019</p>
          </div>
          <h3 class="btn-warning rounded" id="acc">Achievement</h3>
          <div class="bg-white" id="acc-panel">
            <p>Surviving in Fasilkom till now</p>
            <p>Completing Pre-Proposal, TP SDA, story 8, Adbis, Alin, and bidding in a week</p>
          </div>
          <div class="g-signin2" data-onsuccess="onSignIn"></div>
      </div>
    </div>
  </div>
{% endblock %}

Lab6/templates/subscribe.html
{% extends 'navbar.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
  Story PPW
{% endblock title %}

{% block extrahead %}
    <link rel="stylesheet" type= 'text/css' href="{% static 'style.css' %}">
    <script src="{% static 'js/story10.js' %}"></script>
{% endblock %}


{% block content %}

<body onload="myFunction()" style="margin:0;">
  <div id="loader"></div>

  <div style="display:none;" id="myDiv" class="animate-bottom">
    <div class="container text-left">
      <h3 class="btn btn-dark" id="id_change">Change Theme</h3>
    </div>
    <h1 class="center-text" id="hello" align='center'>Subscribe Now!</h1>
    <p align="center" id="header-description">Fill the form below to subscribe this website</p>
    <br>
    <div class="cell medium-1"></div>
    <div class="cell medium-4" style="padding-left: 25%; padding-right:25%">
        <div id="alertt"></div>
        <form class='form-group' id='subsform' method='POST' action="{% url 'Lab6:add_subs' %}">
            <div>
                {% csrf_token %}
                {% for fields in form %}
                    {{ fields.label_tag }}
                    {{ fields }}
                {% endfor %}
            </div>
            <br>
            <div align="center">
                <button class='btn btn-default' id='subs-button' type="submit">Subscribe!</button>
            </div>
        </form>
        <br>
        <br>
        <hr>
        <h1 class="center-text" id="hello1" align='center'>Our Subscriber</h1>
        <div id='list-subscriber'>
            <br>
            <center>
                <table class="table" id='subs-table'>
                    <tr>
                        <thead>
                            <th scope="col">No</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Status</th>
                        </thead>
                    </tr>
                    <tbody></tbody>
                </table>
            </center>
        </div>
    </div>
    <div class="cell medium-1"></div>

{% endblock %}